config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/auth/github', as: :github_login
  get '/auth/twitter', as: :twitter_login
  get '/auth/:provider/callback', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'

  resources :groups, only: [:new, :create, :edit, :update, :destroy] do
    resource :follows, module: :groups, only: [:update, :destroy]
  end

  resources :follows, only: [:create]
  delete :follows, to: 'follows#destroy'
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  def self.find_from_oauth(auth_data)
    find_by_provider_and_uid(auth_data[:provider], auth_data[:uid])
  end

  def self.create_from_user_and_oauth(user, auth_data)
    Authorization.create(
      user_id:  user.id,
      provider: auth_data[:provider],
      uid:      auth_data[:uid],
      token:    auth_data[:credentials][:token],
      secret:   auth_data[:credentials][:secret],
      username: auth_data[:info][:nickname]
    )
  end

  def logo_for_service
    Service.find_by(provider: self.provider).logo
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, uniqueness: true

  has_many :group_users
  has_many :users, through: :group_users

  def owner
    User.find_by(id: self.owner_id)
  end

end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :provider, uniqueness: true

  has_many :service_users
  has_many :users, through: :service_users

end

app/models/service_factory.rb
class ServiceFactory

  def self.create_service(logged_in_user, service_name)
    create_service_class(service_name).new(user_auth_info(logged_in_user, service_name))
  end


  private

  def self.user_auth_info(logged_in_user, service_name)
    logged_in_user.authorizations.find_by_provider(service_name)
  end

  def self.create_service_class(name)
    "#{name.to_s.capitalize}Service".constantize
  end
end

app/models/service_user.rb
class ServiceUser < ActiveRecord::Base
  belongs_to :service
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :service_users
  has_many :services, through: :service_users

  def self.create_from_oauth(auth_data)
    user = User.create(name: auth_data[:info][:name], image_url: auth_data[:info][:image])
    user.add_new_service(auth_data)

    user
  end

  def inactive_services()
    Service.all - self.services
  end

  def username_for_service(service)
    self.authorizations.find_by(provider: service.provider).username
  end

  def add_new_service(auth_data)
    self.services << Service.find_by(provider: auth_data[:provider])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to root_path unless current_user
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_user

  def index
    @groups = Group.all
    @owned_groups = Group.where(owner_id: current_user.id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :require_user

  def create
    allowed_params.each do |user_id, data|
      data.each do |service, data|
        ServiceFactory.create_service(current_user, service).follow(user_to_follow(data, service)) unless following_yourself?(user_id)
      end
    end

    redirect_to dashboard_path
  end

  def destroy
    allowed_params.each do |user_id, data|
      data.each do |service, data|
        ServiceFactory.create_service(current_user, service).unfollow(user_to_follow(data, service)) unless following_yourself?(user_id)
      end
    end

    redirect_to dashboard_path
  end


  private

  def following_yourself?(id)
    current_user == User.find_by(id: id)
  end

  def user_to_follow(data, service)
    Authorization.find_by_provider_and_uid(service, data[:user_to_follow_uid]).username
  end

  # https://github.com/rails/rails/issues/9454
  def allowed_params
    params.require(:follows).permit!
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user
  before_action :require_group_owner, only: [:edit, :update, :destroy]

  def new
    @group = Group.new
    @users = User.order(:name)
    @owner_id = current_user.id
  end

  def create
    group = Group.new(allowed_params)

    if group.save
      add_users_to(group)
    end

    redirect_to dashboard_path
  end

  def edit
    @group = current_group
    @users = User.order(:name)
  end

  def update
    group = current_group

    if group
      group.update_attributes(allowed_params)
      add_users_to(group)
    end

    redirect_to dashboard_path
  end

  def destroy
    group = current_group

    if group
      group.delete
    end

    redirect_to dashboard_path
  end


  private

  def current_group
    Group.find_by(id: params[:id])
  end

  def allowed_params
    params.require(:group).permit(:name, :description, :owner_id, user_ids: [])
  end

  def user_ids_to_add
    allowed_params[:user_ids].reject(&:empty?)
  end

  def add_users_to(group)
    group.user_ids = user_ids_to_add
  end

  def require_group_owner
    redirect_to dashboard_path unless current_group.owner_id == current_user.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to dashboard_path if current_user
  end

  def create
    auth_data = request.env["omniauth.auth"]
    auth      = Authorization.find_from_oauth(auth_data)

    if provider_already_authorized?(auth)
      login_user_with_id(auth.user_id)
    elsif user_already_logged_in?
      add_new_authorization_for(current_user, auth_data)
      add_new_service_for(current_user, auth_data)
    else
      user = create_new_user(auth_data)
      add_new_authorization_for(user, auth_data)
      login_user_with_id(user.id)
    end

    redirect_to dashboard_path
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  def login_user_with_id(id)
    session[:user_id] = id
  end

  def provider_already_authorized?(auth)
    !!auth
  end

  def user_already_logged_in?
    !!current_user
  end

  def add_new_authorization_for(user, auth_data)
    Authorization.create_from_user_and_oauth(user, auth_data)
  end

  def add_new_service_for(user, auth_data)
    user.add_new_service(auth_data)
  end

  def create_new_user(auth_data)
    User.create_from_oauth(auth_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_filterbar.html.erb
<div class="row">
  <form class="col s12">
    <div class="row">

      <div class="input-field col s10">
        <input type="text" id="group-filter">
        <label for="group-filter">Filter</label>
      </div>

      <div class="input-field col s2">
        <input type="checkbox" id="group-owned-filter">
        <label for="group-owned-filter">Owned</label>
      </div>

    </div>
  </form>
</div>

app/views/dashboard/_follows.submit.button.html.erb
<%= form_tag follows_path, method: method_to_use do %>

  <%= fields_for :follows do |follows| %>

    <% users.each do |user| %>

      <%= follows.fields_for user.id.to_s do |user_id| %>

        <% user.authorizations.each do |auth| %>

          <%= user_id.fields_for auth.provider do |provider| %>
            <%= provider.hidden_field "user_to_follow_uid", value: auth.uid %>
          <% end %>

        <% end %>

      <% end %>

    <% end %>

  <% end %>

  <%= button_tag type: :submit, class: button_classes do %>
    <i class="my-icon material-icons"><%= button_icon %></i>
  <% end %>

<% end %>

app/views/dashboard/_group.header.html.erb
<ul class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header">
      <div class="row center-align">

        <div class="col s4">
          Owner
        </div>
        <div class="col s2">
          Name
        </div>
        <div class="col s3">
          Description
        </div>
        <div class="col s1">
          Members
        </div>
        <div class="col s2">
        </div>
        <div class="col s2">
        </div>
      </div>
    </div>
  </li>
</ul>

app/views/dashboard/_group.html.erb
<ul class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header">
      <%= render partial: "dashboard/group.row", locals: { group: group } %>
    </div>
    <div class="collapsible-body">
      <%= render partial: "dashboard/users", locals: { users: group.users } %>
    </div>
  </li>
</ul>

app/views/dashboard/_group.row.html.erb
<div class="row center-align group-row">
  <div class="col s3 group-owner">
    <div><%= image_tag group.owner.image_url, class: "responsive-img circle noob-small" %></div>
    <div><%= group.owner.name %></div>
  </div>
  <div class="col s2 group-name">
    <%= group.name %>
  </div>
  <div class="col s4 group-description">
    <%= group.description %>
  </div>
  <div class="col s1 group-members">
    <%= group.users.count %>
  </div>
  <div class="col s2">

    <%= render partial: "follows.submit.button",
               locals:  {
                 method_to_use: "post",
                 button_icon: "add_circle",
                 button_classes: "btn-floating btn waves-effect waves-light group-all-btn",
                 users: group.users
               } %>

    <%= render partial: "follows.submit.button",
               locals:  {
                 method_to_use: "delete",
                 button_icon: "remove_circle",
                 button_classes: "btn-floating btn waves-effect waves-light red group-all-btn",
                 users: group.users
               } %>
  </div>

</div>

app/views/dashboard/_group.submit.button.html.erb
<%= form_tag follows_path, method: method_to_use do %>

  <%= fields_for :follows do |follows| %>

    <% users.each do |user| %>

      <%= follows.fields_for user.id.to_s do |user_id| %>

        <% user.authorizations.each do |auth| %>

          <%= user_id.fields_for auth.provider do |provider| %>
            <%= provider.hidden_field "user_to_follow_uid", value: auth.uid %>
          <% end %>

        <% end %>

      <% end %>

    <% end %>

  <% end %>

  <%= button_tag type: :submit, class: button_classes do %>
    <i class="medium material-icons"><%= button_icon %></i>
  <% end %>

<% end %>

app/views/dashboard/_profile.current.user.html.erb
<div class="card">
  <div class="card-image">
    <%= image_tag user.image_url, class: "responsive-img" %>
  </div>
  <div class="card-content black-text">
    <div class="card-panel">
      <h6 class="center-align">Hello <%= user.name %>!</h6>
    </div>

    <div class="collection with-header">
      <div class="collection-item collection-header">
        <div class="center-align">
          <h5>Accounts</h5>
        </div>
      </div>

      <% active_services.each do |service| %>
        <div class="collection-item row">
          <div class="valign col s4">
            <%= image_tag service.logo, class: "responsive-img noob-small" %>
          </div>
          <div class="valign col s8">
            <h5 class="center-align"><%= user.username_for_service(service) %></h5>
          </div>
        </div>
      <% end %>

      <% inactive_services.each do |service| %>
        <div class="collection-item">
          <div class="valign row">
            <div class="col s4 valign">
              <%= image_tag service.logo, class: "responsive-img circle noob-small" %>
            </div>
            <div class="col s8 valign right-align">
              <%= link_to "Add", eval("#{service.provider}_login_path"), class: "waves-effect waves-light btn-flat" %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/dashboard/_profile.groups.html.erb
<div class="card" id="owned-groups">
  <div class="card-content black-text">
    <div class="collection with-header">

      <div class="collection-item collection-header">
        <div class="center-align">
          <h5>Owned Groups</h5>
        </div>
      </div>
      <%= render partial: "profile.groups.list", collection: groups, as: "group" %>
      <div class="collection-item">
        <div class="center-align">
          <h6><%= link_to "Create Group", new_group_path, class: "waves-effect waves-light btn" %></h6>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_profile.groups.list.html.erb
<div class="collection-item">
  <div class="row valign-wrapper override-row-bottom-margin">
    <div class="col s4 m3 valign">
      <%= group.name %>
    </div>
    <div class="col s4 m3 valign">
      <%= link_to("Edit", edit_group_path(group), class: "waves-effect waves-light btn-flat") %>
    </div>
    <div class="col s4 m6 valign">
      <%= link_to("Remove", group, method: :delete, class: "waves-effect waves-light btn-flat") %>
    </div>
  </div>
</div>

app/views/dashboard/_profile.html.erb
<div id="profile">

  <%= render partial: "profile.current.user", locals: {
                                                user:              current_user,
                                                authorizations:    current_user.authorizations,
                                                active_services:   current_user.services,
                                                inactive_services: current_user.inactive_services
                                            } %>

  <%= render partial: "profile.groups", locals: { groups: @owned_groups } %>

</div>

app/views/dashboard/_users.html.erb
<ul class="collection with-header">

  <table class="group-users">
    <thead>
    <tr>
      <th data-field="username">Name</th>
      <th data-field="provider">Authorized Providers</th>
      <th>Action</th>
    </tr>
    </thead>

    <tbody>

    <% users.each do |user| %>
      <tr class="group-user-row">
        <td class="user-name">
          <div><%=  image_tag user.image_url, class: "responsive-img circle noob-small" %></div>
          <div><%= user.name %></div>
        </td>
        <td>
          <% user.authorizations.each do |auth| %>
            <%= image_tag auth.logo_for_service, class: "responsive-img circle noob-small" %>
          <% end %>
        </td>
        <td>
          <% if current_user == user %>
            <% disable = "disabled" %>
          <% else %>
            <% disable = "" %>
          <% end %>

          <%= render partial: "follows.submit.button",
                     locals:  {
                       method_to_use:  "post",
                       users:          [user],
                       authorizations: user.authorizations,
                       button_icon:    "add_circle",
                       button_classes: "btn-floating btn waves-effect waves-light #{disable} user-follow-btn"
                     } %>

          <%= render partial: "follows.submit.button",
                     locals:  {
                       method_to_use:  "delete",
                       users:          [user],
                       authorizations: user.authorizations,
                       button_icon:    "remove_circle",
                       button_classes: "btn-floating btn waves-effect waves-light red #{disable} user-follow-btn"
                     } %>

        </td>
      </tr>
    <% end %>

    </tbody>

  </table>

</ul>

app/views/dashboard/index.html.erb
<%= render partial: "layouts/header" %>

<main class="white">

  <div class="row">
    <div class="col s4 m3 white">
      <%= render "dashboard/profile" %>
    </div>

    <div class="col s8 m9 white" id="groups">
      <% if @groups %>
        <%= render partial: "dashboard/group.header" %>
        <%= render partial: "dashboard/group", collection: @groups %>
      <% end %>
    </div>

  </div>

</main>

app/views/groups/_form.html.erb
<div class="row section">
  <div class="col s8 m6 offset-s2 offset-m3">
    <div class="card-panel">
      <%= form_for group do |f| %>
        <div class="row">

          <div class="input-field col s12">
            <%= f.text_field :name %>
            <%= f.label :name %>
          </div>

          <div class="input-field col s12">
            <%= f.text_field :description %>
            <%= f.label :description %>
          </div>

          <%= f.label :users %>
          <%= f.collection_check_boxes :user_ids, users, :id, :name do |b| %>
            <p>
              <%= b.check_box %>
              <%= b.label %>
            </p>
          <% end %>

          <%= f.hidden_field :owner_id, value: owner_id %>

          <% if !group.new_record? %>
            <%= hidden_field_tag "_method", "put" %>
          <% end %>

          <%= f.submit group.new_record? ? "Create Group" : "Update Group", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render partial: "layouts/header" %>

<%= render partial: "form", locals: { group: @group, users: @users, owner_id: current_user.id } %>

app/views/groups/new.html.erb
<%= render partial: "layouts/header" %>

<%= render partial: "form", locals: { group: @group, users: @users, owner_id: @owner_id } %>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper" id="navbar">
        <%= link_to "Cannected", root_path, class: "brand-logo left" %>
        <ul class="right">
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cannected</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>

<%= yield %>

</body>
</html>